### PR TITLE
Expanded on player details

### PR DESCRIPTION
**Pull request by cp6**
Added 2 functions: one gets player steam name, avatar and profile url
the other gets the game name of the appid. these details are then used throughout the page.

### CODE REVIEW

**Comment by montyanderson** [comment]
Thank you! It's awesome people are helping maintain a repository I made when I was 12/13 :)
Is there a reason you changed it from spaces to tabs, or the other way around?

**Comment by cp6** [comment]
Not a problem :) Are you talking about the spacing's? if so i have a habit of pressing the format button in PHPstorm and that would have caused it.

**Comment by montyanderson** [comment]
Ah, what's PHPstorm - is it an IDE?

**Comment by montyanderson** [comment]
I'll sort some of the formatting out then merge this later.
I'm at work at the moment.

**Comment by cp6** [comment]
Yea its an ide, thats fine.

**Pull request closed without merging**
